# Generated by Django 5.2.6 on 2025-09-08 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Имя",
                    models.CharField(
                        max_length=90, unique=True, verbose_name="Имя поста"
                    ),
                ),
                ("Содержание", models.TextField(verbose_name="Содержание")),
                (
                    "Дата создания",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "Дата изменения",
                    models.DateField(auto_now_add=True, verbose_name="Дата изменения"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-Имя"],
            },
        ),
    ]
