# Generated by Django 5.2.6 on 2025-09-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Текст комментария")),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комменатрии",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=90, unique=True, verbose_name="Имя поста"
                    ),
                ),
                ("text", models.TextField(verbose_name="Содержание")),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата изменения"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=90, unique=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-title"],
            },
        ),
    ]
