# Generated by Django 5.2.6 on 2025-09-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-title"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.RenameField(
            model_name="post",
            old_name="Дата создания",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="Содержание",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="Имя",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="Дата изменения",
            new_name="updated_date",
        ),
    ]
