# Generated by Django 5.2.6 on 2025-09-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(
                blank=True, max_length=512, null=True, verbose_name="Описание"
            ),
        ),
    ]
