# Generated by Django 5.2.6 on 2025-09-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="answer",
            field=models.ManyToManyField(blank=True, null=True, to="posts.comments"),
        ),
    ]
