# Generated by Django 5.2.6 on 2025-09-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_comments_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="answer",
            field=models.ManyToManyField(blank=True, to="posts.comments"),
        ),
    ]
