# Generated by Django 5.2.6 on 2025-11-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_category_alter_comments_comment_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="comment",
            field=models.TextField(verbose_name=""),
        ),
    ]
