# Generated by Django 5.2.6 on 2025-11-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_comments_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/posts", verbose_name="Обложка"
            ),
        ),
    ]
