# Generated by Django 5.2.6 on 2025-11-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_post_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="posts", verbose_name="Обложка"
            ),
        ),
    ]
