# Generated by Django 6.0.1 on 2026-02-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_tag_alter_post_text_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
