# Generated by Django 5.2.6 on 2025-09-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(null=True, verbose_name="Дата рождения"),
        ),
    ]
