# Generated by Django 5.2.6 on 2025-09-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_comments_answer"),
        ("users", "0002_alter_customuser_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, to="posts.post", verbose_name="Избранное"
            ),
        ),
    ]
