# Generated by Django 5.2.6 on 2025-09-25 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="blog_following",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Подписки"
            ),
        ),
    ]
