# Generated by Django 5.2.6 on 2025-11-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_blog_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                default="", max_length=80, null=True, verbose_name="Статус"
            ),
        ),
    ]
