# Generated by Django 5.2.6 on 2025-11-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="users", verbose_name="Аватар"
            ),
        ),
    ]
