# Generated by Django 6.0.1 on 2026-02-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Статус'),
        ),
    ]
