version: "5"
services:
  django:
    container_name: django
    build: .
    tty: true
    ports:
      - 8000:8000
    restart: always
    volumes:
      - .:/project/
    environment:
      - DB_PASS=root
      - DB_USER=root
      - DB_NAME=project
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=root
      - EMAIL_HOST_USER=yourmail@ya.ru
      - EMAIL_HOST_PASSWORD=secretkey
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:18.3-alpine3.23
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=project
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  redis:
    image: redis:8.6.2-alpine3.23
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=root
      - REDIS_USER=root
      - REDIS_USER_PASSWORD=root

  celery:
    container_name: celery
    restart: always
    build: .
    command: celery -A core worker -l INFO -E
    volumes:
      - .:/project/
    depends_on:
      - postgres
      - redis
      - django
    environment:
      - DB_NAME=project
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - EMAIL_HOST_USER=yourhostmail@ya.ru
      - EMAIL_HOST_PASSWORD=secretkey
volumes:
  pgdata:
