# Generated by Django 5.2.6 on 2025-09-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blognote",
            name="title",
            field=models.CharField(max_length=90, verbose_name="Заголовок"),
        ),
    ]
