# Generated by Django 5.2.6 on 2025-09-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blognote_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blognote",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новость"),
        ),
    ]
