# Generated by Django 5.2.6 on 2025-09-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blognote_is_new"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blognote",
            old_name="is_new",
            new_name="is_news",
        ),
    ]
