# Generated by Django 5.2.6 on 2025-12-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_is_new_blognote_is_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="blognote",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="news", verbose_name="Обложка"
            ),
        ),
    ]
