# Generated by Django 6.0.1 on 2026-02-07 07:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blognote_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognote',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
    ]
