# Generated by Django 6.0.1 on 2026-03-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blognote_text'),
        ('posts', '0010_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognote',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.comments', verbose_name='Комментарии'),
        ),
    ]
