# Generated by Django 6.0.1 on 2026-03-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Имя")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Описание товара",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="Цена")),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="products", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["-name"],
            },
        ),
    ]
